[package]
name = "apm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_info = "3.8.2"
clap = "4.5.13"
indicatif = "0.17.8"