name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
            operating_system: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.operating_system }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

    - name: Test 
      run: cargo test 

    - name: Check
      run: cargo check 

    - name: Bench
      run: cargo bench

    - name: Doc
      run: cargo bench

    - uses: actions/upload-artifact@v3
      with:
        name: apm-docs
        path: ${{ runner.workspace }}/Apm/target/doc
