name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        operating_system: [ubuntu-latest, windows-latest, macintosh-latest]
    runs-on: ${{ matrix.operating_system }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Format
        run: cargo fmt --all -- --check
