name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    strategy:
      matrix:
        operating_system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating_system }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Test 
      run: cargo test 

    - name: Check
      run: cargo check 

    - name: Format
      run: cargo fmt --all -- --check

    - name: Bench
      run: cargo bench

    - name: Docs
      run: cargo doc

    - uses: actions/upload-artifact@v4
      with:
        name: apm-docs
        path: ${{ runner.workspace }}/Apm/target/doc